spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          okta:
            #client-id: 0oad2f9lm1tDEZUCf0h7
            #client-secret: G2Gh5INi8aVgtbI391ssmfLRcxu4vXHk1wa2I36V
            client-id: 0oaqe30ehktWRO6j35d6
            client-secret: DbtAH9N4gOczAkh-C5AVQu1MPBKDBMH4XTrU_9Jo
            redirectUri: http://localhost:8099/okta
        provider:
          okta:
            authorization-uri: https://dev-158606.oktapreview.com/oauth2/default/v1/authorize
            token-uri: https://dev-158606.oktapreview.com/oauth2/default/v1/token
            user-info-uri: https://dev-158606.oktapreview.com/oauth2/default/v1/userinfo
            user-name-attribute: preferred_username
            jwk-set-uri: https://dev-158606.oktapreview.com/oauth2/default/v1/keys
